# Base configs
#baseurl: "https://raymonddelgado.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: ""

# UI configs
title: "Raymond Delgado"
subtitle: "Design Director"
author: ""
header:
 title: "Raymond Delgado © 2019"
 subtitle: ""
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""
#social_urls:
#  facebook: ""
#  twitter: ""
#  instagram: ""
#  dribbble: ""
#  linkedin: ""
#github: ""